load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "resources",
    srcs = ["resources.go"],
    importpath = "github.com/eat-pray-ai/yutu/cmd/resources",
    visibility = ["//visibility:public"],
    deps = [
        "//cmd/abuseReport",
        "//cmd/activity",
        "//cmd/caption",
        "//cmd/channel",
        "//cmd/channelBanner",
        "//cmd/channelSection",
        "//cmd/comment",
        "//cmd/commentThread",
        "//cmd/i18nLanguage",
        "//cmd/i18nRegion",
        "//cmd/liveBroadcast",
        "//cmd/liveChatBan",
        "//cmd/liveChatMessage",
        "//cmd/liveChatModerator",
        "//cmd/liveStream",
        "//cmd/member",
        "//cmd/membershipsLevel",
        "//cmd/playlist",
        "//cmd/playlistImage",
        "//cmd/playlistItem",
        "//cmd/search",
        "//cmd/subscription",
        "//cmd/superChatEvent",
        "//cmd/thirdPartyLink",
        "//cmd/thumbnail",
        "//cmd/video",
        "//cmd/videoAbuseReportReason",
        "//cmd/videoCategory",
        "//cmd/watermark",
    ],
)
